include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

stages:
  - lint
  - build-and-publish

default:
  tags:
    - kubernetes

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED

build-and-publish-buildkitd:
  stage: build-and-publish
  image: docker-registry.wikimedia.org/releng/buildctl:0.10.4-4
  # These are provided by the buildkitd environment
  # variables:
  #   http_proxy: "http://webproxy:8080"
  #   https_proxy: "http://webproxy:8080"
  #   no_proxy: "127.0.0.1,::1,localhost,.wmnet,.wikimedia.org,.wikipedia.org,.wikibooks.org,.wikiquote.org,.wiktionary.org,.wikisource.org,.wikispecies.org,.wikiversity.org,.wikidata.org,.mediawiki.org,.wikinews.org,.wikivoyage.org"
  script:
    - mkdir ~/.docker
    - |
      echo "$CI_JOB_JWT" | jq --raw-input '{ auths: { "docker-registry.discovery.wmnet": { registrytoken: . } } }' > ~/.docker/config.json
    - IMAGE_TAG=$(printf "%s" "${CI_COMMIT_REF_NAME}" | tr -c 'a-zA-Z0-9_.-' - | cut -c -128)
    - wmf/build.sh
      --opt build-arg:http_proxy="$http_proxy"
      --opt build-arg:https_proxy="$https_proxy"
      --opt build-arg:no_proxy="$no_proxy"
      --output type=image,name="docker-registry.discovery.wmnet/repos/releng/buildkit:${IMAGE_TAG}",push=true
  tags:
    - protected
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED

lint-helm-chart:
  stage: lint
  extends: .kokkuri:build-and-run-image
  variables:
    BUILD_VARIANT: helm-lint
    BUILD_CONFIG: wmf/blubber.yaml
    RUN_ARGUMENTS: '["wmf/charts/buildkitd"]'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - wmf/charts/**/*
        - wmf/blubber.yaml

package-and-publish-helm-chart:
  stage: build-and-publish
  extends: .kokkuri:build-image
  variables:
    BUILD_VARIANT: helm-package
    BUILD_CONFIG: wmf/blubber.yaml
    BUILDCTL_BUILD_FLAGS: '--output type=local,dest=wmf/charts'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - wmf/charts/**/*
        - wmf/blubber.yaml
  artifacts:
    paths:
      - wmf/charts/buildkitd.tgz
