---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildkitd.fullname" . }}
  labels:
    {{- include "buildkitd.labels" . | nindent 4 }}
data:
  buildkitd.toml: |
    {{- range .Values.insecureRegistries }}
    [registry.{{ . | quote }}]
      http = true
    {{- end }}
